// Code generated by protoc-gen-zig
///! package transit_realtime
const std = @import("std");

const protobuf = @import("protobuf");
const fd = protobuf.fd;

/// The contents of a feed message.
/// A feed is a continuous stream of feed messages. Each message in the stream is
/// obtained as a response to an appropriate HTTP GET request.
/// A realtime feed is always defined with relation to an existing GTFS feed.
/// All the entity ids are resolved with respect to the GTFS feed.
/// Note that "required" and "optional" as stated in this file refer to Protocol
/// Buffer cardinality, not semantic cardinality.  See reference.md at
/// https://github.com/google/transit/tree/master/gtfs-realtime for field
/// semantic cardinality.
pub const FeedMessage = struct {
    header: ?FeedHeader = null,
    entity: std.ArrayList(FeedEntity) = .empty,

    pub const _desc_table = .{
        .header = fd(1, .submessage),
        .entity = fd(2, .{ .repeated = .submessage }),
    };

    /// Encodes the message to the writer
    /// The allocator is used to generate submessages internally.
    /// Hence, an ArenaAllocator is a preferred choice if allocations are a bottleneck.
    pub fn encode(
        self: @This(),
        writer: *std.Io.Writer,
        allocator: std.mem.Allocator,
    ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
        return protobuf.encode(writer, allocator, self);
    }

    /// Decodes the message from the bytes read from the reader.
    pub fn decode(
        reader: *std.Io.Reader,
        allocator: std.mem.Allocator,
    ) (protobuf.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
        return protobuf.decode(@This(), reader, allocator);
    }

    /// Streaming pull-decoder: walks a `std.Io.Reader` one wire
    /// field at a time without allocating. See `src/stream.zig`.
    pub const StreamDecoder = protobuf.StreamDecoder(@This());

    /// Deinitializes and frees the memory associated with the message.
    pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
        return protobuf.deinit(allocator, self);
    }

    /// Duplicates the message.
    pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
        return protobuf.dupe(@This(), self, allocator);
    }

    /// Decodes the message from the JSON string.
    pub fn jsonDecode(
        input: []const u8,
        options: std.json.ParseOptions,
        allocator: std.mem.Allocator,
    ) !std.json.Parsed(@This()) {
        return protobuf.json.decode(@This(), input, options, allocator);
    }

    /// Encodes the message to a JSON string.
    pub fn jsonEncode(
        self: @This(),
        options: std.json.Stringify.Options,
        pb_options: protobuf.json.Options,
        allocator: std.mem.Allocator,
    ) ![]const u8 {
        return protobuf.json.encode(self, options, pb_options, allocator);
    }

    /// This method is used by std.json
    /// internally for deserialization. DO NOT RENAME!
    pub fn jsonParse(
        allocator: std.mem.Allocator,
        source: anytype,
        options: std.json.ParseOptions,
    ) !@This() {
        return protobuf.json.parse(@This(), allocator, source, options);
    }
};

/// Metadata about a feed, included in feed messages.
pub const FeedHeader = struct {
    gtfs_realtime_version: []const u8,
    incrementality: ?FeedHeader.Incrementality = .FULL_DATASET,
    timestamp: ?u64 = null,
    feed_version: ?[]const u8 = null,

    pub const _desc_table = .{
        .gtfs_realtime_version = fd(1, .{ .scalar = .string }),
        .incrementality = fd(2, .@"enum"),
        .timestamp = fd(3, .{ .scalar = .uint64 }),
        .feed_version = fd(4, .{ .scalar = .string }),
    };

    /// Determines whether the current fetch is incremental.  Currently,
    /// DIFFERENTIAL mode is unsupported and behavior is unspecified for feeds
    /// that use this mode.  There are discussions on the GTFS Realtime mailing
    /// list around fully specifying the behavior of DIFFERENTIAL mode and the
    /// documentation will be updated when those discussions are finalized.
    pub const Incrementality = enum(i32) {
        FULL_DATASET = 0,
        DIFFERENTIAL = 1,
        _,
    };

    /// Encodes the message to the writer
    /// The allocator is used to generate submessages internally.
    /// Hence, an ArenaAllocator is a preferred choice if allocations are a bottleneck.
    pub fn encode(
        self: @This(),
        writer: *std.Io.Writer,
        allocator: std.mem.Allocator,
    ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
        return protobuf.encode(writer, allocator, self);
    }

    /// Decodes the message from the bytes read from the reader.
    pub fn decode(
        reader: *std.Io.Reader,
        allocator: std.mem.Allocator,
    ) (protobuf.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
        return protobuf.decode(@This(), reader, allocator);
    }

    /// Streaming pull-decoder: walks a `std.Io.Reader` one wire
    /// field at a time without allocating. See `src/stream.zig`.
    pub const StreamDecoder = protobuf.StreamDecoder(@This());

    /// Deinitializes and frees the memory associated with the message.
    pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
        return protobuf.deinit(allocator, self);
    }

    /// Duplicates the message.
    pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
        return protobuf.dupe(@This(), self, allocator);
    }

    /// Decodes the message from the JSON string.
    pub fn jsonDecode(
        input: []const u8,
        options: std.json.ParseOptions,
        allocator: std.mem.Allocator,
    ) !std.json.Parsed(@This()) {
        return protobuf.json.decode(@This(), input, options, allocator);
    }

    /// Encodes the message to a JSON string.
    pub fn jsonEncode(
        self: @This(),
        options: std.json.Stringify.Options,
        pb_options: protobuf.json.Options,
        allocator: std.mem.Allocator,
    ) ![]const u8 {
        return protobuf.json.encode(self, options, pb_options, allocator);
    }

    /// This method is used by std.json
    /// internally for deserialization. DO NOT RENAME!
    pub fn jsonParse(
        allocator: std.mem.Allocator,
        source: anytype,
        options: std.json.ParseOptions,
    ) !@This() {
        return protobuf.json.parse(@This(), allocator, source, options);
    }
};

/// A definition (or update) of an entity in the transit feed.
pub const FeedEntity = struct {
    id: []const u8,
    is_deleted: ?bool = false,
    trip_update: ?TripUpdate = null,
    vehicle: ?VehiclePosition = null,
    alert: ?Alert = null,
    shape: ?Shape = null,
    stop: ?Stop = null,
    trip_modifications: ?TripModifications = null,

    pub const _desc_table = .{
        .id = fd(1, .{ .scalar = .string }),
        .is_deleted = fd(2, .{ .scalar = .bool }),
        .trip_update = fd(3, .submessage),
        .vehicle = fd(4, .submessage),
        .alert = fd(5, .submessage),
        .shape = fd(6, .submessage),
        .stop = fd(7, .submessage),
        .trip_modifications = fd(8, .submessage),
    };

    /// Encodes the message to the writer
    /// The allocator is used to generate submessages internally.
    /// Hence, an ArenaAllocator is a preferred choice if allocations are a bottleneck.
    pub fn encode(
        self: @This(),
        writer: *std.Io.Writer,
        allocator: std.mem.Allocator,
    ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
        return protobuf.encode(writer, allocator, self);
    }

    /// Decodes the message from the bytes read from the reader.
    pub fn decode(
        reader: *std.Io.Reader,
        allocator: std.mem.Allocator,
    ) (protobuf.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
        return protobuf.decode(@This(), reader, allocator);
    }

    /// Streaming pull-decoder: walks a `std.Io.Reader` one wire
    /// field at a time without allocating. See `src/stream.zig`.
    pub const StreamDecoder = protobuf.StreamDecoder(@This());

    /// Deinitializes and frees the memory associated with the message.
    pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
        return protobuf.deinit(allocator, self);
    }

    /// Duplicates the message.
    pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
        return protobuf.dupe(@This(), self, allocator);
    }

    /// Decodes the message from the JSON string.
    pub fn jsonDecode(
        input: []const u8,
        options: std.json.ParseOptions,
        allocator: std.mem.Allocator,
    ) !std.json.Parsed(@This()) {
        return protobuf.json.decode(@This(), input, options, allocator);
    }

    /// Encodes the message to a JSON string.
    pub fn jsonEncode(
        self: @This(),
        options: std.json.Stringify.Options,
        pb_options: protobuf.json.Options,
        allocator: std.mem.Allocator,
    ) ![]const u8 {
        return protobuf.json.encode(self, options, pb_options, allocator);
    }

    /// This method is used by std.json
    /// internally for deserialization. DO NOT RENAME!
    pub fn jsonParse(
        allocator: std.mem.Allocator,
        source: anytype,
        options: std.json.ParseOptions,
    ) !@This() {
        return protobuf.json.parse(@This(), allocator, source, options);
    }
};

/// Realtime update of the progress of a vehicle along a trip.
/// Depending on the value of ScheduleRelationship, a TripUpdate can specify:
/// - A trip that proceeds along the schedule.
/// - A trip that proceeds along a route but has no fixed schedule.
/// - A trip that have been added or removed with regard to schedule.
///
/// The updates can be for future, predicted arrival/departure events, or for
/// past events that already occurred.
/// Normally, updates should get more precise and more certain (see
/// uncertainty below) as the events gets closer to current time.
/// Even if that is not possible, the information for past events should be
/// precise and certain. In particular, if an update points to time in the past
/// but its update's uncertainty is not 0, the client should conclude that the
/// update is a (wrong) prediction and that the trip has not completed yet.
///
/// Note that the update can describe a trip that is already completed.
/// To this end, it is enough to provide an update for the last stop of the trip.
/// If the time of that is in the past, the client will conclude from that that
/// the whole trip is in the past (it is possible, although inconsequential, to
/// also provide updates for preceding stops).
/// This option is most relevant for a trip that has completed ahead of schedule,
/// but according to the schedule, the trip is still proceeding at the current
/// time. Removing the updates for this trip could make the client assume
/// that the trip is still proceeding.
/// Note that the feed provider is allowed, but not required, to purge past
/// updates - this is one case where this would be practically useful.
pub const TripUpdate = struct {
    trip: ?TripDescriptor = null,
    vehicle: ?VehicleDescriptor = null,
    stop_time_update: std.ArrayList(TripUpdate.StopTimeUpdate) = .empty,
    timestamp: ?u64 = null,
    delay: ?i32 = null,
    trip_properties: ?TripUpdate.TripProperties = null,

    pub const _desc_table = .{
        .trip = fd(1, .submessage),
        .vehicle = fd(3, .submessage),
        .stop_time_update = fd(2, .{ .repeated = .submessage }),
        .timestamp = fd(4, .{ .scalar = .uint64 }),
        .delay = fd(5, .{ .scalar = .int32 }),
        .trip_properties = fd(6, .submessage),
    };

    /// Timing information for a single predicted event (either arrival or
    /// departure).
    /// Timing consists of delay and/or estimated time, and uncertainty.
    /// - delay should be used when the prediction is given relative to some
    /// existing schedule in GTFS.
    /// - time should be given whether there is a predicted schedule or not. If
    /// both time and delay are specified, time will take precedence
    /// (although normally, time, if given for a scheduled trip, should be
    /// equal to scheduled time in GTFS + delay).
    ///
    /// Uncertainty applies equally to both time and delay.
    /// The uncertainty roughly specifies the expected error in true delay (but
    /// note, we don't yet define its precise statistical meaning). It's possible
    /// for the uncertainty to be 0, for example for trains that are driven under
    /// computer timing control.
    pub const StopTimeEvent = struct {
        delay: ?i32 = null,
        time: ?i64 = null,
        uncertainty: ?i32 = null,
        scheduled_time: ?i64 = null,

        pub const _desc_table = .{
            .delay = fd(1, .{ .scalar = .int32 }),
            .time = fd(2, .{ .scalar = .int64 }),
            .uncertainty = fd(3, .{ .scalar = .int32 }),
            .scheduled_time = fd(4, .{ .scalar = .int64 }),
        };

        /// Encodes the message to the writer
        /// The allocator is used to generate submessages internally.
        /// Hence, an ArenaAllocator is a preferred choice if allocations are a bottleneck.
        pub fn encode(
            self: @This(),
            writer: *std.Io.Writer,
            allocator: std.mem.Allocator,
        ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
            return protobuf.encode(writer, allocator, self);
        }

        /// Decodes the message from the bytes read from the reader.
        pub fn decode(
            reader: *std.Io.Reader,
            allocator: std.mem.Allocator,
        ) (protobuf.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
            return protobuf.decode(@This(), reader, allocator);
        }

        /// Streaming pull-decoder: walks a `std.Io.Reader` one wire
        /// field at a time without allocating. See `src/stream.zig`.
        pub const StreamDecoder = protobuf.StreamDecoder(@This());

        /// Deinitializes and frees the memory associated with the message.
        pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
            return protobuf.deinit(allocator, self);
        }

        /// Duplicates the message.
        pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
            return protobuf.dupe(@This(), self, allocator);
        }

        /// Decodes the message from the JSON string.
        pub fn jsonDecode(
            input: []const u8,
            options: std.json.ParseOptions,
            allocator: std.mem.Allocator,
        ) !std.json.Parsed(@This()) {
            return protobuf.json.decode(@This(), input, options, allocator);
        }

        /// Encodes the message to a JSON string.
        pub fn jsonEncode(
            self: @This(),
            options: std.json.Stringify.Options,
            pb_options: protobuf.json.Options,
            allocator: std.mem.Allocator,
        ) ![]const u8 {
            return protobuf.json.encode(self, options, pb_options, allocator);
        }

        /// This method is used by std.json
        /// internally for deserialization. DO NOT RENAME!
        pub fn jsonParse(
            allocator: std.mem.Allocator,
            source: anytype,
            options: std.json.ParseOptions,
        ) !@This() {
            return protobuf.json.parse(@This(), allocator, source, options);
        }
    };

    /// Realtime update for arrival and/or departure events for a given stop on a
    /// trip. Updates can be supplied for both past and future events.
    /// The producer is allowed, although not required, to drop past events.
    pub const StopTimeUpdate = struct {
        stop_sequence: ?u32 = null,
        stop_id: ?[]const u8 = null,
        arrival: ?TripUpdate.StopTimeEvent = null,
        departure: ?TripUpdate.StopTimeEvent = null,
        departure_occupancy_status: ?VehiclePosition.OccupancyStatus = null,
        schedule_relationship: ?TripUpdate.StopTimeUpdate.ScheduleRelationship = .SCHEDULED,
        stop_time_properties: ?TripUpdate.StopTimeUpdate.StopTimeProperties = null,

        pub const _desc_table = .{
            .stop_sequence = fd(1, .{ .scalar = .uint32 }),
            .stop_id = fd(4, .{ .scalar = .string }),
            .arrival = fd(2, .submessage),
            .departure = fd(3, .submessage),
            .departure_occupancy_status = fd(7, .@"enum"),
            .schedule_relationship = fd(5, .@"enum"),
            .stop_time_properties = fd(6, .submessage),
        };

        /// The relation between the StopTimeEvents and the static schedule.
        pub const ScheduleRelationship = enum(i32) {
            SCHEDULED = 0,
            SKIPPED = 1,
            NO_DATA = 2,
            UNSCHEDULED = 3,
            _,
        };

        /// Provides the updated values for the stop time.
        /// NOTE: This message is still experimental, and subject to change. It may be formally adopted in the future.
        pub const StopTimeProperties = struct {
            assigned_stop_id: ?[]const u8 = null,
            stop_headsign: ?[]const u8 = null,
            pickup_type: ?TripUpdate.StopTimeUpdate.StopTimeProperties.DropOffPickupType = null,
            drop_off_type: ?TripUpdate.StopTimeUpdate.StopTimeProperties.DropOffPickupType = null,

            pub const _desc_table = .{
                .assigned_stop_id = fd(1, .{ .scalar = .string }),
                .stop_headsign = fd(2, .{ .scalar = .string }),
                .pickup_type = fd(3, .@"enum"),
                .drop_off_type = fd(4, .@"enum"),
            };

            pub const DropOffPickupType = enum(i32) {
                REGULAR = 0,
                NONE = 1,
                PHONE_AGENCY = 2,
                COORDINATE_WITH_DRIVER = 3,
                _,
            };

            /// Encodes the message to the writer
            /// The allocator is used to generate submessages internally.
            /// Hence, an ArenaAllocator is a preferred choice if allocations are a bottleneck.
            pub fn encode(
                self: @This(),
                writer: *std.Io.Writer,
                allocator: std.mem.Allocator,
            ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
                return protobuf.encode(writer, allocator, self);
            }

            /// Decodes the message from the bytes read from the reader.
            pub fn decode(
                reader: *std.Io.Reader,
                allocator: std.mem.Allocator,
            ) (protobuf.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
                return protobuf.decode(@This(), reader, allocator);
            }

            /// Streaming pull-decoder: walks a `std.Io.Reader` one wire
            /// field at a time without allocating. See `src/stream.zig`.
            pub const StreamDecoder = protobuf.StreamDecoder(@This());

            /// Deinitializes and frees the memory associated with the message.
            pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
                return protobuf.deinit(allocator, self);
            }

            /// Duplicates the message.
            pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
                return protobuf.dupe(@This(), self, allocator);
            }

            /// Decodes the message from the JSON string.
            pub fn jsonDecode(
                input: []const u8,
                options: std.json.ParseOptions,
                allocator: std.mem.Allocator,
            ) !std.json.Parsed(@This()) {
                return protobuf.json.decode(@This(), input, options, allocator);
            }

            /// Encodes the message to a JSON string.
            pub fn jsonEncode(
                self: @This(),
                options: std.json.Stringify.Options,
                pb_options: protobuf.json.Options,
                allocator: std.mem.Allocator,
            ) ![]const u8 {
                return protobuf.json.encode(self, options, pb_options, allocator);
            }

            /// This method is used by std.json
            /// internally for deserialization. DO NOT RENAME!
            pub fn jsonParse(
                allocator: std.mem.Allocator,
                source: anytype,
                options: std.json.ParseOptions,
            ) !@This() {
                return protobuf.json.parse(@This(), allocator, source, options);
            }
        };

        /// Encodes the message to the writer
        /// The allocator is used to generate submessages internally.
        /// Hence, an ArenaAllocator is a preferred choice if allocations are a bottleneck.
        pub fn encode(
            self: @This(),
            writer: *std.Io.Writer,
            allocator: std.mem.Allocator,
        ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
            return protobuf.encode(writer, allocator, self);
        }

        /// Decodes the message from the bytes read from the reader.
        pub fn decode(
            reader: *std.Io.Reader,
            allocator: std.mem.Allocator,
        ) (protobuf.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
            return protobuf.decode(@This(), reader, allocator);
        }

        /// Streaming pull-decoder: walks a `std.Io.Reader` one wire
        /// field at a time without allocating. See `src/stream.zig`.
        pub const StreamDecoder = protobuf.StreamDecoder(@This());

        /// Deinitializes and frees the memory associated with the message.
        pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
            return protobuf.deinit(allocator, self);
        }

        /// Duplicates the message.
        pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
            return protobuf.dupe(@This(), self, allocator);
        }

        /// Decodes the message from the JSON string.
        pub fn jsonDecode(
            input: []const u8,
            options: std.json.ParseOptions,
            allocator: std.mem.Allocator,
        ) !std.json.Parsed(@This()) {
            return protobuf.json.decode(@This(), input, options, allocator);
        }

        /// Encodes the message to a JSON string.
        pub fn jsonEncode(
            self: @This(),
            options: std.json.Stringify.Options,
            pb_options: protobuf.json.Options,
            allocator: std.mem.Allocator,
        ) ![]const u8 {
            return protobuf.json.encode(self, options, pb_options, allocator);
        }

        /// This method is used by std.json
        /// internally for deserialization. DO NOT RENAME!
        pub fn jsonParse(
            allocator: std.mem.Allocator,
            source: anytype,
            options: std.json.ParseOptions,
        ) !@This() {
            return protobuf.json.parse(@This(), allocator, source, options);
        }
    };

    /// Defines updated properties of the trip, such as a new shape_id when there is a detour. Or defines the
    /// trip_id, start_date, and start_time of a DUPLICATED trip.
    /// NOTE: This message is still experimental, and subject to change. It may be formally adopted in the future.
    pub const TripProperties = struct {
        trip_id: ?[]const u8 = null,
        start_date: ?[]const u8 = null,
        start_time: ?[]const u8 = null,
        shape_id: ?[]const u8 = null,
        trip_headsign: ?[]const u8 = null,
        trip_short_name: ?[]const u8 = null,

        pub const _desc_table = .{
            .trip_id = fd(1, .{ .scalar = .string }),
            .start_date = fd(2, .{ .scalar = .string }),
            .start_time = fd(3, .{ .scalar = .string }),
            .shape_id = fd(4, .{ .scalar = .string }),
            .trip_headsign = fd(5, .{ .scalar = .string }),
            .trip_short_name = fd(6, .{ .scalar = .string }),
        };

        /// Encodes the message to the writer
        /// The allocator is used to generate submessages internally.
        /// Hence, an ArenaAllocator is a preferred choice if allocations are a bottleneck.
        pub fn encode(
            self: @This(),
            writer: *std.Io.Writer,
            allocator: std.mem.Allocator,
        ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
            return protobuf.encode(writer, allocator, self);
        }

        /// Decodes the message from the bytes read from the reader.
        pub fn decode(
            reader: *std.Io.Reader,
            allocator: std.mem.Allocator,
        ) (protobuf.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
            return protobuf.decode(@This(), reader, allocator);
        }

        /// Streaming pull-decoder: walks a `std.Io.Reader` one wire
        /// field at a time without allocating. See `src/stream.zig`.
        pub const StreamDecoder = protobuf.StreamDecoder(@This());

        /// Deinitializes and frees the memory associated with the message.
        pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
            return protobuf.deinit(allocator, self);
        }

        /// Duplicates the message.
        pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
            return protobuf.dupe(@This(), self, allocator);
        }

        /// Decodes the message from the JSON string.
        pub fn jsonDecode(
            input: []const u8,
            options: std.json.ParseOptions,
            allocator: std.mem.Allocator,
        ) !std.json.Parsed(@This()) {
            return protobuf.json.decode(@This(), input, options, allocator);
        }

        /// Encodes the message to a JSON string.
        pub fn jsonEncode(
            self: @This(),
            options: std.json.Stringify.Options,
            pb_options: protobuf.json.Options,
            allocator: std.mem.Allocator,
        ) ![]const u8 {
            return protobuf.json.encode(self, options, pb_options, allocator);
        }

        /// This method is used by std.json
        /// internally for deserialization. DO NOT RENAME!
        pub fn jsonParse(
            allocator: std.mem.Allocator,
            source: anytype,
            options: std.json.ParseOptions,
        ) !@This() {
            return protobuf.json.parse(@This(), allocator, source, options);
        }
    };

    /// Encodes the message to the writer
    /// The allocator is used to generate submessages internally.
    /// Hence, an ArenaAllocator is a preferred choice if allocations are a bottleneck.
    pub fn encode(
        self: @This(),
        writer: *std.Io.Writer,
        allocator: std.mem.Allocator,
    ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
        return protobuf.encode(writer, allocator, self);
    }

    /// Decodes the message from the bytes read from the reader.
    pub fn decode(
        reader: *std.Io.Reader,
        allocator: std.mem.Allocator,
    ) (protobuf.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
        return protobuf.decode(@This(), reader, allocator);
    }

    /// Streaming pull-decoder: walks a `std.Io.Reader` one wire
    /// field at a time without allocating. See `src/stream.zig`.
    pub const StreamDecoder = protobuf.StreamDecoder(@This());

    /// Deinitializes and frees the memory associated with the message.
    pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
        return protobuf.deinit(allocator, self);
    }

    /// Duplicates the message.
    pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
        return protobuf.dupe(@This(), self, allocator);
    }

    /// Decodes the message from the JSON string.
    pub fn jsonDecode(
        input: []const u8,
        options: std.json.ParseOptions,
        allocator: std.mem.Allocator,
    ) !std.json.Parsed(@This()) {
        return protobuf.json.decode(@This(), input, options, allocator);
    }

    /// Encodes the message to a JSON string.
    pub fn jsonEncode(
        self: @This(),
        options: std.json.Stringify.Options,
        pb_options: protobuf.json.Options,
        allocator: std.mem.Allocator,
    ) ![]const u8 {
        return protobuf.json.encode(self, options, pb_options, allocator);
    }

    /// This method is used by std.json
    /// internally for deserialization. DO NOT RENAME!
    pub fn jsonParse(
        allocator: std.mem.Allocator,
        source: anytype,
        options: std.json.ParseOptions,
    ) !@This() {
        return protobuf.json.parse(@This(), allocator, source, options);
    }
};

/// Realtime positioning information for a given vehicle.
pub const VehiclePosition = struct {
    trip: ?TripDescriptor = null,
    vehicle: ?VehicleDescriptor = null,
    position: ?Position = null,
    current_stop_sequence: ?u32 = null,
    stop_id: ?[]const u8 = null,
    current_status: ?VehiclePosition.VehicleStopStatus = .IN_TRANSIT_TO,
    timestamp: ?u64 = null,
    congestion_level: ?VehiclePosition.CongestionLevel = null,
    occupancy_status: ?VehiclePosition.OccupancyStatus = null,
    occupancy_percentage: ?u32 = null,
    multi_carriage_details: std.ArrayList(VehiclePosition.CarriageDetails) = .empty,

    pub const _desc_table = .{
        .trip = fd(1, .submessage),
        .vehicle = fd(8, .submessage),
        .position = fd(2, .submessage),
        .current_stop_sequence = fd(3, .{ .scalar = .uint32 }),
        .stop_id = fd(7, .{ .scalar = .string }),
        .current_status = fd(4, .@"enum"),
        .timestamp = fd(5, .{ .scalar = .uint64 }),
        .congestion_level = fd(6, .@"enum"),
        .occupancy_status = fd(9, .@"enum"),
        .occupancy_percentage = fd(10, .{ .scalar = .uint32 }),
        .multi_carriage_details = fd(11, .{ .repeated = .submessage }),
    };

    pub const VehicleStopStatus = enum(i32) {
        INCOMING_AT = 0,
        STOPPED_AT = 1,
        IN_TRANSIT_TO = 2,
        _,
    };

    /// Congestion level that is affecting this vehicle.
    pub const CongestionLevel = enum(i32) {
        UNKNOWN_CONGESTION_LEVEL = 0,
        RUNNING_SMOOTHLY = 1,
        STOP_AND_GO = 2,
        CONGESTION = 3,
        SEVERE_CONGESTION = 4,
        _,
    };

    /// The state of passenger occupancy for the vehicle or carriage.
    /// Individual producers may not publish all OccupancyStatus values. Therefore, consumers
    /// must not assume that the OccupancyStatus values follow a linear scale.
    /// Consumers should represent OccupancyStatus values as the state indicated
    /// and intended by the producer. Likewise, producers must use OccupancyStatus values that
    /// correspond to actual vehicle occupancy states.
    /// For describing passenger occupancy levels on a linear scale, see `occupancy_percentage`.
    /// This field is still experimental, and subject to change. It may be formally adopted in the future.
    pub const OccupancyStatus = enum(i32) {
        EMPTY = 0,
        MANY_SEATS_AVAILABLE = 1,
        FEW_SEATS_AVAILABLE = 2,
        STANDING_ROOM_ONLY = 3,
        CRUSHED_STANDING_ROOM_ONLY = 4,
        FULL = 5,
        NOT_ACCEPTING_PASSENGERS = 6,
        NO_DATA_AVAILABLE = 7,
        NOT_BOARDABLE = 8,
        _,
    };

    /// Carriage specific details, used for vehicles composed of several carriages
    /// This message/field is still experimental, and subject to change. It may be formally adopted in the future.
    pub const CarriageDetails = struct {
        id: ?[]const u8 = null,
        label: ?[]const u8 = null,
        occupancy_status: ?VehiclePosition.OccupancyStatus = .NO_DATA_AVAILABLE,
        occupancy_percentage: ?i32 = -1,
        carriage_sequence: ?u32 = null,

        pub const _desc_table = .{
            .id = fd(1, .{ .scalar = .string }),
            .label = fd(2, .{ .scalar = .string }),
            .occupancy_status = fd(3, .@"enum"),
            .occupancy_percentage = fd(4, .{ .scalar = .int32 }),
            .carriage_sequence = fd(5, .{ .scalar = .uint32 }),
        };

        /// Encodes the message to the writer
        /// The allocator is used to generate submessages internally.
        /// Hence, an ArenaAllocator is a preferred choice if allocations are a bottleneck.
        pub fn encode(
            self: @This(),
            writer: *std.Io.Writer,
            allocator: std.mem.Allocator,
        ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
            return protobuf.encode(writer, allocator, self);
        }

        /// Decodes the message from the bytes read from the reader.
        pub fn decode(
            reader: *std.Io.Reader,
            allocator: std.mem.Allocator,
        ) (protobuf.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
            return protobuf.decode(@This(), reader, allocator);
        }

        /// Streaming pull-decoder: walks a `std.Io.Reader` one wire
        /// field at a time without allocating. See `src/stream.zig`.
        pub const StreamDecoder = protobuf.StreamDecoder(@This());

        /// Deinitializes and frees the memory associated with the message.
        pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
            return protobuf.deinit(allocator, self);
        }

        /// Duplicates the message.
        pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
            return protobuf.dupe(@This(), self, allocator);
        }

        /// Decodes the message from the JSON string.
        pub fn jsonDecode(
            input: []const u8,
            options: std.json.ParseOptions,
            allocator: std.mem.Allocator,
        ) !std.json.Parsed(@This()) {
            return protobuf.json.decode(@This(), input, options, allocator);
        }

        /// Encodes the message to a JSON string.
        pub fn jsonEncode(
            self: @This(),
            options: std.json.Stringify.Options,
            pb_options: protobuf.json.Options,
            allocator: std.mem.Allocator,
        ) ![]const u8 {
            return protobuf.json.encode(self, options, pb_options, allocator);
        }

        /// This method is used by std.json
        /// internally for deserialization. DO NOT RENAME!
        pub fn jsonParse(
            allocator: std.mem.Allocator,
            source: anytype,
            options: std.json.ParseOptions,
        ) !@This() {
            return protobuf.json.parse(@This(), allocator, source, options);
        }
    };

    /// Encodes the message to the writer
    /// The allocator is used to generate submessages internally.
    /// Hence, an ArenaAllocator is a preferred choice if allocations are a bottleneck.
    pub fn encode(
        self: @This(),
        writer: *std.Io.Writer,
        allocator: std.mem.Allocator,
    ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
        return protobuf.encode(writer, allocator, self);
    }

    /// Decodes the message from the bytes read from the reader.
    pub fn decode(
        reader: *std.Io.Reader,
        allocator: std.mem.Allocator,
    ) (protobuf.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
        return protobuf.decode(@This(), reader, allocator);
    }

    /// Streaming pull-decoder: walks a `std.Io.Reader` one wire
    /// field at a time without allocating. See `src/stream.zig`.
    pub const StreamDecoder = protobuf.StreamDecoder(@This());

    /// Deinitializes and frees the memory associated with the message.
    pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
        return protobuf.deinit(allocator, self);
    }

    /// Duplicates the message.
    pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
        return protobuf.dupe(@This(), self, allocator);
    }

    /// Decodes the message from the JSON string.
    pub fn jsonDecode(
        input: []const u8,
        options: std.json.ParseOptions,
        allocator: std.mem.Allocator,
    ) !std.json.Parsed(@This()) {
        return protobuf.json.decode(@This(), input, options, allocator);
    }

    /// Encodes the message to a JSON string.
    pub fn jsonEncode(
        self: @This(),
        options: std.json.Stringify.Options,
        pb_options: protobuf.json.Options,
        allocator: std.mem.Allocator,
    ) ![]const u8 {
        return protobuf.json.encode(self, options, pb_options, allocator);
    }

    /// This method is used by std.json
    /// internally for deserialization. DO NOT RENAME!
    pub fn jsonParse(
        allocator: std.mem.Allocator,
        source: anytype,
        options: std.json.ParseOptions,
    ) !@This() {
        return protobuf.json.parse(@This(), allocator, source, options);
    }
};

/// An alert, indicating some sort of incident in the public transit network.
pub const Alert = struct {
    active_period: std.ArrayList(TimeRange) = .empty,
    communication_period: std.ArrayList(TimeRange) = .empty,
    impact_period: std.ArrayList(TimeRange) = .empty,
    informed_entity: std.ArrayList(EntitySelector) = .empty,
    cause: ?Alert.Cause = .UNKNOWN_CAUSE,
    effect: ?Alert.Effect = .UNKNOWN_EFFECT,
    url: ?TranslatedString = null,
    header_text: ?TranslatedString = null,
    description_text: ?TranslatedString = null,
    tts_header_text: ?TranslatedString = null,
    tts_description_text: ?TranslatedString = null,
    severity_level: ?Alert.SeverityLevel = .UNKNOWN_SEVERITY,
    image: ?TranslatedImage = null,
    image_alternative_text: ?TranslatedString = null,
    cause_detail: ?TranslatedString = null,
    effect_detail: ?TranslatedString = null,

    pub const _desc_table = .{
        .active_period = fd(1, .{ .repeated = .submessage }),
        .communication_period = fd(2, .{ .repeated = .submessage }),
        .impact_period = fd(3, .{ .repeated = .submessage }),
        .informed_entity = fd(5, .{ .repeated = .submessage }),
        .cause = fd(6, .@"enum"),
        .effect = fd(7, .@"enum"),
        .url = fd(8, .submessage),
        .header_text = fd(10, .submessage),
        .description_text = fd(11, .submessage),
        .tts_header_text = fd(12, .submessage),
        .tts_description_text = fd(13, .submessage),
        .severity_level = fd(14, .@"enum"),
        .image = fd(15, .submessage),
        .image_alternative_text = fd(16, .submessage),
        .cause_detail = fd(17, .submessage),
        .effect_detail = fd(18, .submessage),
    };

    /// Cause of this alert. If cause_detail is included, then Cause must also be included.
    pub const Cause = enum(i32) {
        UNKNOWN_CAUSE = 1,
        OTHER_CAUSE = 2,
        TECHNICAL_PROBLEM = 3,
        STRIKE = 4,
        DEMONSTRATION = 5,
        ACCIDENT = 6,
        HOLIDAY = 7,
        WEATHER = 8,
        MAINTENANCE = 9,
        CONSTRUCTION = 10,
        POLICE_ACTIVITY = 11,
        MEDICAL_EMERGENCY = 12,
        SPECIAL_EVENT = 13,
        _,
    };

    /// What is the effect of this problem on the affected entity. If effect_detail is included, then Effect must also be included.
    pub const Effect = enum(i32) {
        NO_SERVICE = 1,
        REDUCED_SERVICE = 2,
        SIGNIFICANT_DELAYS = 3,
        DETOUR = 4,
        ADDITIONAL_SERVICE = 5,
        MODIFIED_SERVICE = 6,
        OTHER_EFFECT = 7,
        UNKNOWN_EFFECT = 8,
        STOP_MOVED = 9,
        NO_EFFECT = 10,
        ACCESSIBILITY_ISSUE = 11,
        _,
    };

    /// Severity of this alert.
    pub const SeverityLevel = enum(i32) {
        UNKNOWN_SEVERITY = 1,
        INFO = 2,
        WARNING = 3,
        SEVERE = 4,
        _,
    };

    /// Encodes the message to the writer
    /// The allocator is used to generate submessages internally.
    /// Hence, an ArenaAllocator is a preferred choice if allocations are a bottleneck.
    pub fn encode(
        self: @This(),
        writer: *std.Io.Writer,
        allocator: std.mem.Allocator,
    ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
        return protobuf.encode(writer, allocator, self);
    }

    /// Decodes the message from the bytes read from the reader.
    pub fn decode(
        reader: *std.Io.Reader,
        allocator: std.mem.Allocator,
    ) (protobuf.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
        return protobuf.decode(@This(), reader, allocator);
    }

    /// Streaming pull-decoder: walks a `std.Io.Reader` one wire
    /// field at a time without allocating. See `src/stream.zig`.
    pub const StreamDecoder = protobuf.StreamDecoder(@This());

    /// Deinitializes and frees the memory associated with the message.
    pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
        return protobuf.deinit(allocator, self);
    }

    /// Duplicates the message.
    pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
        return protobuf.dupe(@This(), self, allocator);
    }

    /// Decodes the message from the JSON string.
    pub fn jsonDecode(
        input: []const u8,
        options: std.json.ParseOptions,
        allocator: std.mem.Allocator,
    ) !std.json.Parsed(@This()) {
        return protobuf.json.decode(@This(), input, options, allocator);
    }

    /// Encodes the message to a JSON string.
    pub fn jsonEncode(
        self: @This(),
        options: std.json.Stringify.Options,
        pb_options: protobuf.json.Options,
        allocator: std.mem.Allocator,
    ) ![]const u8 {
        return protobuf.json.encode(self, options, pb_options, allocator);
    }

    /// This method is used by std.json
    /// internally for deserialization. DO NOT RENAME!
    pub fn jsonParse(
        allocator: std.mem.Allocator,
        source: anytype,
        options: std.json.ParseOptions,
    ) !@This() {
        return protobuf.json.parse(@This(), allocator, source, options);
    }
};

/// A time interval. The interval is considered active at time 't' if 't' is
/// greater than or equal to the start time and less than the end time.
pub const TimeRange = struct {
    start: ?u64 = null,
    end: ?u64 = null,

    pub const _desc_table = .{
        .start = fd(1, .{ .scalar = .uint64 }),
        .end = fd(2, .{ .scalar = .uint64 }),
    };

    /// Encodes the message to the writer
    /// The allocator is used to generate submessages internally.
    /// Hence, an ArenaAllocator is a preferred choice if allocations are a bottleneck.
    pub fn encode(
        self: @This(),
        writer: *std.Io.Writer,
        allocator: std.mem.Allocator,
    ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
        return protobuf.encode(writer, allocator, self);
    }

    /// Decodes the message from the bytes read from the reader.
    pub fn decode(
        reader: *std.Io.Reader,
        allocator: std.mem.Allocator,
    ) (protobuf.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
        return protobuf.decode(@This(), reader, allocator);
    }

    /// Streaming pull-decoder: walks a `std.Io.Reader` one wire
    /// field at a time without allocating. See `src/stream.zig`.
    pub const StreamDecoder = protobuf.StreamDecoder(@This());

    /// Deinitializes and frees the memory associated with the message.
    pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
        return protobuf.deinit(allocator, self);
    }

    /// Duplicates the message.
    pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
        return protobuf.dupe(@This(), self, allocator);
    }

    /// Decodes the message from the JSON string.
    pub fn jsonDecode(
        input: []const u8,
        options: std.json.ParseOptions,
        allocator: std.mem.Allocator,
    ) !std.json.Parsed(@This()) {
        return protobuf.json.decode(@This(), input, options, allocator);
    }

    /// Encodes the message to a JSON string.
    pub fn jsonEncode(
        self: @This(),
        options: std.json.Stringify.Options,
        pb_options: protobuf.json.Options,
        allocator: std.mem.Allocator,
    ) ![]const u8 {
        return protobuf.json.encode(self, options, pb_options, allocator);
    }

    /// This method is used by std.json
    /// internally for deserialization. DO NOT RENAME!
    pub fn jsonParse(
        allocator: std.mem.Allocator,
        source: anytype,
        options: std.json.ParseOptions,
    ) !@This() {
        return protobuf.json.parse(@This(), allocator, source, options);
    }
};

/// A position.
pub const Position = struct {
    latitude: f32,
    longitude: f32,
    bearing: ?f32 = null,
    odometer: ?f64 = null,
    speed: ?f32 = null,

    pub const _desc_table = .{
        .latitude = fd(1, .{ .scalar = .float }),
        .longitude = fd(2, .{ .scalar = .float }),
        .bearing = fd(3, .{ .scalar = .float }),
        .odometer = fd(4, .{ .scalar = .double }),
        .speed = fd(5, .{ .scalar = .float }),
    };

    /// Encodes the message to the writer
    /// The allocator is used to generate submessages internally.
    /// Hence, an ArenaAllocator is a preferred choice if allocations are a bottleneck.
    pub fn encode(
        self: @This(),
        writer: *std.Io.Writer,
        allocator: std.mem.Allocator,
    ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
        return protobuf.encode(writer, allocator, self);
    }

    /// Decodes the message from the bytes read from the reader.
    pub fn decode(
        reader: *std.Io.Reader,
        allocator: std.mem.Allocator,
    ) (protobuf.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
        return protobuf.decode(@This(), reader, allocator);
    }

    /// Streaming pull-decoder: walks a `std.Io.Reader` one wire
    /// field at a time without allocating. See `src/stream.zig`.
    pub const StreamDecoder = protobuf.StreamDecoder(@This());

    /// Deinitializes and frees the memory associated with the message.
    pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
        return protobuf.deinit(allocator, self);
    }

    /// Duplicates the message.
    pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
        return protobuf.dupe(@This(), self, allocator);
    }

    /// Decodes the message from the JSON string.
    pub fn jsonDecode(
        input: []const u8,
        options: std.json.ParseOptions,
        allocator: std.mem.Allocator,
    ) !std.json.Parsed(@This()) {
        return protobuf.json.decode(@This(), input, options, allocator);
    }

    /// Encodes the message to a JSON string.
    pub fn jsonEncode(
        self: @This(),
        options: std.json.Stringify.Options,
        pb_options: protobuf.json.Options,
        allocator: std.mem.Allocator,
    ) ![]const u8 {
        return protobuf.json.encode(self, options, pb_options, allocator);
    }

    /// This method is used by std.json
    /// internally for deserialization. DO NOT RENAME!
    pub fn jsonParse(
        allocator: std.mem.Allocator,
        source: anytype,
        options: std.json.ParseOptions,
    ) !@This() {
        return protobuf.json.parse(@This(), allocator, source, options);
    }
};

/// A descriptor that identifies an instance of a GTFS trip, or all instances of
/// a trip along a route.
/// - To specify a single trip instance, the trip_id (and if necessary,
/// start_time) is set. If route_id is also set, then it should be same as one
/// that the given trip corresponds to.
/// - To specify all the trips along a given route, only the route_id should be
/// set. Note that if the trip_id is not known, then stop sequence ids in
/// TripUpdate are not sufficient, and stop_ids must be provided as well. In
/// addition, absolute arrival/departure times must be provided.
pub const TripDescriptor = struct {
    trip_id: ?[]const u8 = null,
    route_id: ?[]const u8 = null,
    direction_id: ?u32 = null,
    start_time: ?[]const u8 = null,
    start_date: ?[]const u8 = null,
    schedule_relationship: ?TripDescriptor.ScheduleRelationship = null,
    modified_trip: ?TripDescriptor.ModifiedTripSelector = null,

    pub const _desc_table = .{
        .trip_id = fd(1, .{ .scalar = .string }),
        .route_id = fd(5, .{ .scalar = .string }),
        .direction_id = fd(6, .{ .scalar = .uint32 }),
        .start_time = fd(2, .{ .scalar = .string }),
        .start_date = fd(3, .{ .scalar = .string }),
        .schedule_relationship = fd(4, .@"enum"),
        .modified_trip = fd(7, .submessage),
    };

    /// The relation between this trip and the static schedule. If a trip is done
    /// in accordance with temporary schedule, not reflected in GTFS, then it
    /// shouldn't be marked as SCHEDULED, but likely as ADDED.
    pub const ScheduleRelationship = enum(i32) {
        SCHEDULED = 0,
        ADDED = 1,
        UNSCHEDULED = 2,
        CANCELED = 3,
        REPLACEMENT = 5,
        DUPLICATED = 6,
        DELETED = 7,
        NEW = 8,
        _,
    };

    pub const ModifiedTripSelector = struct {
        modifications_id: ?[]const u8 = null,
        affected_trip_id: ?[]const u8 = null,
        start_time: ?[]const u8 = null,
        start_date: ?[]const u8 = null,

        pub const _desc_table = .{
            .modifications_id = fd(1, .{ .scalar = .string }),
            .affected_trip_id = fd(2, .{ .scalar = .string }),
            .start_time = fd(3, .{ .scalar = .string }),
            .start_date = fd(4, .{ .scalar = .string }),
        };

        /// Encodes the message to the writer
        /// The allocator is used to generate submessages internally.
        /// Hence, an ArenaAllocator is a preferred choice if allocations are a bottleneck.
        pub fn encode(
            self: @This(),
            writer: *std.Io.Writer,
            allocator: std.mem.Allocator,
        ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
            return protobuf.encode(writer, allocator, self);
        }

        /// Decodes the message from the bytes read from the reader.
        pub fn decode(
            reader: *std.Io.Reader,
            allocator: std.mem.Allocator,
        ) (protobuf.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
            return protobuf.decode(@This(), reader, allocator);
        }

        /// Streaming pull-decoder: walks a `std.Io.Reader` one wire
        /// field at a time without allocating. See `src/stream.zig`.
        pub const StreamDecoder = protobuf.StreamDecoder(@This());

        /// Deinitializes and frees the memory associated with the message.
        pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
            return protobuf.deinit(allocator, self);
        }

        /// Duplicates the message.
        pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
            return protobuf.dupe(@This(), self, allocator);
        }

        /// Decodes the message from the JSON string.
        pub fn jsonDecode(
            input: []const u8,
            options: std.json.ParseOptions,
            allocator: std.mem.Allocator,
        ) !std.json.Parsed(@This()) {
            return protobuf.json.decode(@This(), input, options, allocator);
        }

        /// Encodes the message to a JSON string.
        pub fn jsonEncode(
            self: @This(),
            options: std.json.Stringify.Options,
            pb_options: protobuf.json.Options,
            allocator: std.mem.Allocator,
        ) ![]const u8 {
            return protobuf.json.encode(self, options, pb_options, allocator);
        }

        /// This method is used by std.json
        /// internally for deserialization. DO NOT RENAME!
        pub fn jsonParse(
            allocator: std.mem.Allocator,
            source: anytype,
            options: std.json.ParseOptions,
        ) !@This() {
            return protobuf.json.parse(@This(), allocator, source, options);
        }
    };

    /// Encodes the message to the writer
    /// The allocator is used to generate submessages internally.
    /// Hence, an ArenaAllocator is a preferred choice if allocations are a bottleneck.
    pub fn encode(
        self: @This(),
        writer: *std.Io.Writer,
        allocator: std.mem.Allocator,
    ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
        return protobuf.encode(writer, allocator, self);
    }

    /// Decodes the message from the bytes read from the reader.
    pub fn decode(
        reader: *std.Io.Reader,
        allocator: std.mem.Allocator,
    ) (protobuf.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
        return protobuf.decode(@This(), reader, allocator);
    }

    /// Streaming pull-decoder: walks a `std.Io.Reader` one wire
    /// field at a time without allocating. See `src/stream.zig`.
    pub const StreamDecoder = protobuf.StreamDecoder(@This());

    /// Deinitializes and frees the memory associated with the message.
    pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
        return protobuf.deinit(allocator, self);
    }

    /// Duplicates the message.
    pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
        return protobuf.dupe(@This(), self, allocator);
    }

    /// Decodes the message from the JSON string.
    pub fn jsonDecode(
        input: []const u8,
        options: std.json.ParseOptions,
        allocator: std.mem.Allocator,
    ) !std.json.Parsed(@This()) {
        return protobuf.json.decode(@This(), input, options, allocator);
    }

    /// Encodes the message to a JSON string.
    pub fn jsonEncode(
        self: @This(),
        options: std.json.Stringify.Options,
        pb_options: protobuf.json.Options,
        allocator: std.mem.Allocator,
    ) ![]const u8 {
        return protobuf.json.encode(self, options, pb_options, allocator);
    }

    /// This method is used by std.json
    /// internally for deserialization. DO NOT RENAME!
    pub fn jsonParse(
        allocator: std.mem.Allocator,
        source: anytype,
        options: std.json.ParseOptions,
    ) !@This() {
        return protobuf.json.parse(@This(), allocator, source, options);
    }
};

/// Identification information for the vehicle performing the trip.
pub const VehicleDescriptor = struct {
    id: ?[]const u8 = null,
    label: ?[]const u8 = null,
    license_plate: ?[]const u8 = null,
    wheelchair_accessible: ?VehicleDescriptor.WheelchairAccessible = .NO_VALUE,

    pub const _desc_table = .{
        .id = fd(1, .{ .scalar = .string }),
        .label = fd(2, .{ .scalar = .string }),
        .license_plate = fd(3, .{ .scalar = .string }),
        .wheelchair_accessible = fd(4, .@"enum"),
    };

    pub const WheelchairAccessible = enum(i32) {
        NO_VALUE = 0,
        UNKNOWN = 1,
        WHEELCHAIR_ACCESSIBLE = 2,
        WHEELCHAIR_INACCESSIBLE = 3,
        _,
    };

    /// Encodes the message to the writer
    /// The allocator is used to generate submessages internally.
    /// Hence, an ArenaAllocator is a preferred choice if allocations are a bottleneck.
    pub fn encode(
        self: @This(),
        writer: *std.Io.Writer,
        allocator: std.mem.Allocator,
    ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
        return protobuf.encode(writer, allocator, self);
    }

    /// Decodes the message from the bytes read from the reader.
    pub fn decode(
        reader: *std.Io.Reader,
        allocator: std.mem.Allocator,
    ) (protobuf.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
        return protobuf.decode(@This(), reader, allocator);
    }

    /// Streaming pull-decoder: walks a `std.Io.Reader` one wire
    /// field at a time without allocating. See `src/stream.zig`.
    pub const StreamDecoder = protobuf.StreamDecoder(@This());

    /// Deinitializes and frees the memory associated with the message.
    pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
        return protobuf.deinit(allocator, self);
    }

    /// Duplicates the message.
    pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
        return protobuf.dupe(@This(), self, allocator);
    }

    /// Decodes the message from the JSON string.
    pub fn jsonDecode(
        input: []const u8,
        options: std.json.ParseOptions,
        allocator: std.mem.Allocator,
    ) !std.json.Parsed(@This()) {
        return protobuf.json.decode(@This(), input, options, allocator);
    }

    /// Encodes the message to a JSON string.
    pub fn jsonEncode(
        self: @This(),
        options: std.json.Stringify.Options,
        pb_options: protobuf.json.Options,
        allocator: std.mem.Allocator,
    ) ![]const u8 {
        return protobuf.json.encode(self, options, pb_options, allocator);
    }

    /// This method is used by std.json
    /// internally for deserialization. DO NOT RENAME!
    pub fn jsonParse(
        allocator: std.mem.Allocator,
        source: anytype,
        options: std.json.ParseOptions,
    ) !@This() {
        return protobuf.json.parse(@This(), allocator, source, options);
    }
};

/// A selector for an entity in a GTFS feed.
pub const EntitySelector = struct {
    agency_id: ?[]const u8 = null,
    route_id: ?[]const u8 = null,
    route_type: ?i32 = null,
    trip: ?TripDescriptor = null,
    stop_id: ?[]const u8 = null,
    direction_id: ?u32 = null,

    pub const _desc_table = .{
        .agency_id = fd(1, .{ .scalar = .string }),
        .route_id = fd(2, .{ .scalar = .string }),
        .route_type = fd(3, .{ .scalar = .int32 }),
        .trip = fd(4, .submessage),
        .stop_id = fd(5, .{ .scalar = .string }),
        .direction_id = fd(6, .{ .scalar = .uint32 }),
    };

    /// Encodes the message to the writer
    /// The allocator is used to generate submessages internally.
    /// Hence, an ArenaAllocator is a preferred choice if allocations are a bottleneck.
    pub fn encode(
        self: @This(),
        writer: *std.Io.Writer,
        allocator: std.mem.Allocator,
    ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
        return protobuf.encode(writer, allocator, self);
    }

    /// Decodes the message from the bytes read from the reader.
    pub fn decode(
        reader: *std.Io.Reader,
        allocator: std.mem.Allocator,
    ) (protobuf.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
        return protobuf.decode(@This(), reader, allocator);
    }

    /// Streaming pull-decoder: walks a `std.Io.Reader` one wire
    /// field at a time without allocating. See `src/stream.zig`.
    pub const StreamDecoder = protobuf.StreamDecoder(@This());

    /// Deinitializes and frees the memory associated with the message.
    pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
        return protobuf.deinit(allocator, self);
    }

    /// Duplicates the message.
    pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
        return protobuf.dupe(@This(), self, allocator);
    }

    /// Decodes the message from the JSON string.
    pub fn jsonDecode(
        input: []const u8,
        options: std.json.ParseOptions,
        allocator: std.mem.Allocator,
    ) !std.json.Parsed(@This()) {
        return protobuf.json.decode(@This(), input, options, allocator);
    }

    /// Encodes the message to a JSON string.
    pub fn jsonEncode(
        self: @This(),
        options: std.json.Stringify.Options,
        pb_options: protobuf.json.Options,
        allocator: std.mem.Allocator,
    ) ![]const u8 {
        return protobuf.json.encode(self, options, pb_options, allocator);
    }

    /// This method is used by std.json
    /// internally for deserialization. DO NOT RENAME!
    pub fn jsonParse(
        allocator: std.mem.Allocator,
        source: anytype,
        options: std.json.ParseOptions,
    ) !@This() {
        return protobuf.json.parse(@This(), allocator, source, options);
    }
};

/// An internationalized message containing per-language versions of a snippet of
/// text or a URL.
/// One of the strings from a message will be picked up. The resolution proceeds
/// as follows:
/// 1. If the UI language matches the language code of a translation,
/// the first matching translation is picked.
/// 2. If a default UI language (e.g., English) matches the language code of a
/// translation, the first matching translation is picked.
/// 3. If some translation has an unspecified language code, that translation is
/// picked.
pub const TranslatedString = struct {
    translation: std.ArrayList(TranslatedString.Translation) = .empty,

    pub const _desc_table = .{
        .translation = fd(1, .{ .repeated = .submessage }),
    };

    pub const Translation = struct {
        text: []const u8,
        language: ?[]const u8 = null,

        pub const _desc_table = .{
            .text = fd(1, .{ .scalar = .string }),
            .language = fd(2, .{ .scalar = .string }),
        };

        /// Encodes the message to the writer
        /// The allocator is used to generate submessages internally.
        /// Hence, an ArenaAllocator is a preferred choice if allocations are a bottleneck.
        pub fn encode(
            self: @This(),
            writer: *std.Io.Writer,
            allocator: std.mem.Allocator,
        ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
            return protobuf.encode(writer, allocator, self);
        }

        /// Decodes the message from the bytes read from the reader.
        pub fn decode(
            reader: *std.Io.Reader,
            allocator: std.mem.Allocator,
        ) (protobuf.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
            return protobuf.decode(@This(), reader, allocator);
        }

        /// Streaming pull-decoder: walks a `std.Io.Reader` one wire
        /// field at a time without allocating. See `src/stream.zig`.
        pub const StreamDecoder = protobuf.StreamDecoder(@This());

        /// Deinitializes and frees the memory associated with the message.
        pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
            return protobuf.deinit(allocator, self);
        }

        /// Duplicates the message.
        pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
            return protobuf.dupe(@This(), self, allocator);
        }

        /// Decodes the message from the JSON string.
        pub fn jsonDecode(
            input: []const u8,
            options: std.json.ParseOptions,
            allocator: std.mem.Allocator,
        ) !std.json.Parsed(@This()) {
            return protobuf.json.decode(@This(), input, options, allocator);
        }

        /// Encodes the message to a JSON string.
        pub fn jsonEncode(
            self: @This(),
            options: std.json.Stringify.Options,
            pb_options: protobuf.json.Options,
            allocator: std.mem.Allocator,
        ) ![]const u8 {
            return protobuf.json.encode(self, options, pb_options, allocator);
        }

        /// This method is used by std.json
        /// internally for deserialization. DO NOT RENAME!
        pub fn jsonParse(
            allocator: std.mem.Allocator,
            source: anytype,
            options: std.json.ParseOptions,
        ) !@This() {
            return protobuf.json.parse(@This(), allocator, source, options);
        }
    };

    /// Encodes the message to the writer
    /// The allocator is used to generate submessages internally.
    /// Hence, an ArenaAllocator is a preferred choice if allocations are a bottleneck.
    pub fn encode(
        self: @This(),
        writer: *std.Io.Writer,
        allocator: std.mem.Allocator,
    ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
        return protobuf.encode(writer, allocator, self);
    }

    /// Decodes the message from the bytes read from the reader.
    pub fn decode(
        reader: *std.Io.Reader,
        allocator: std.mem.Allocator,
    ) (protobuf.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
        return protobuf.decode(@This(), reader, allocator);
    }

    /// Streaming pull-decoder: walks a `std.Io.Reader` one wire
    /// field at a time without allocating. See `src/stream.zig`.
    pub const StreamDecoder = protobuf.StreamDecoder(@This());

    /// Deinitializes and frees the memory associated with the message.
    pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
        return protobuf.deinit(allocator, self);
    }

    /// Duplicates the message.
    pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
        return protobuf.dupe(@This(), self, allocator);
    }

    /// Decodes the message from the JSON string.
    pub fn jsonDecode(
        input: []const u8,
        options: std.json.ParseOptions,
        allocator: std.mem.Allocator,
    ) !std.json.Parsed(@This()) {
        return protobuf.json.decode(@This(), input, options, allocator);
    }

    /// Encodes the message to a JSON string.
    pub fn jsonEncode(
        self: @This(),
        options: std.json.Stringify.Options,
        pb_options: protobuf.json.Options,
        allocator: std.mem.Allocator,
    ) ![]const u8 {
        return protobuf.json.encode(self, options, pb_options, allocator);
    }

    /// This method is used by std.json
    /// internally for deserialization. DO NOT RENAME!
    pub fn jsonParse(
        allocator: std.mem.Allocator,
        source: anytype,
        options: std.json.ParseOptions,
    ) !@This() {
        return protobuf.json.parse(@This(), allocator, source, options);
    }
};

/// An internationalized image containing per-language versions of a URL linking to an image
/// along with meta information
/// Only one of the images from a message will be retained by consumers. The resolution proceeds
/// as follows:
/// 1. If the UI language matches the language code of a translation,
/// the first matching translation is picked.
/// 2. If a default UI language (e.g., English) matches the language code of a
/// translation, the first matching translation is picked.
/// 3. If some translation has an unspecified language code, that translation is
/// picked.
/// NOTE: This field is still experimental, and subject to change. It may be formally adopted in the future.
pub const TranslatedImage = struct {
    localized_image: std.ArrayList(TranslatedImage.LocalizedImage) = .empty,

    pub const _desc_table = .{
        .localized_image = fd(1, .{ .repeated = .submessage }),
    };

    pub const LocalizedImage = struct {
        url: []const u8,
        media_type: []const u8,
        language: ?[]const u8 = null,

        pub const _desc_table = .{
            .url = fd(1, .{ .scalar = .string }),
            .media_type = fd(2, .{ .scalar = .string }),
            .language = fd(3, .{ .scalar = .string }),
        };

        /// Encodes the message to the writer
        /// The allocator is used to generate submessages internally.
        /// Hence, an ArenaAllocator is a preferred choice if allocations are a bottleneck.
        pub fn encode(
            self: @This(),
            writer: *std.Io.Writer,
            allocator: std.mem.Allocator,
        ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
            return protobuf.encode(writer, allocator, self);
        }

        /// Decodes the message from the bytes read from the reader.
        pub fn decode(
            reader: *std.Io.Reader,
            allocator: std.mem.Allocator,
        ) (protobuf.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
            return protobuf.decode(@This(), reader, allocator);
        }

        /// Streaming pull-decoder: walks a `std.Io.Reader` one wire
        /// field at a time without allocating. See `src/stream.zig`.
        pub const StreamDecoder = protobuf.StreamDecoder(@This());

        /// Deinitializes and frees the memory associated with the message.
        pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
            return protobuf.deinit(allocator, self);
        }

        /// Duplicates the message.
        pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
            return protobuf.dupe(@This(), self, allocator);
        }

        /// Decodes the message from the JSON string.
        pub fn jsonDecode(
            input: []const u8,
            options: std.json.ParseOptions,
            allocator: std.mem.Allocator,
        ) !std.json.Parsed(@This()) {
            return protobuf.json.decode(@This(), input, options, allocator);
        }

        /// Encodes the message to a JSON string.
        pub fn jsonEncode(
            self: @This(),
            options: std.json.Stringify.Options,
            pb_options: protobuf.json.Options,
            allocator: std.mem.Allocator,
        ) ![]const u8 {
            return protobuf.json.encode(self, options, pb_options, allocator);
        }

        /// This method is used by std.json
        /// internally for deserialization. DO NOT RENAME!
        pub fn jsonParse(
            allocator: std.mem.Allocator,
            source: anytype,
            options: std.json.ParseOptions,
        ) !@This() {
            return protobuf.json.parse(@This(), allocator, source, options);
        }
    };

    /// Encodes the message to the writer
    /// The allocator is used to generate submessages internally.
    /// Hence, an ArenaAllocator is a preferred choice if allocations are a bottleneck.
    pub fn encode(
        self: @This(),
        writer: *std.Io.Writer,
        allocator: std.mem.Allocator,
    ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
        return protobuf.encode(writer, allocator, self);
    }

    /// Decodes the message from the bytes read from the reader.
    pub fn decode(
        reader: *std.Io.Reader,
        allocator: std.mem.Allocator,
    ) (protobuf.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
        return protobuf.decode(@This(), reader, allocator);
    }

    /// Streaming pull-decoder: walks a `std.Io.Reader` one wire
    /// field at a time without allocating. See `src/stream.zig`.
    pub const StreamDecoder = protobuf.StreamDecoder(@This());

    /// Deinitializes and frees the memory associated with the message.
    pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
        return protobuf.deinit(allocator, self);
    }

    /// Duplicates the message.
    pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
        return protobuf.dupe(@This(), self, allocator);
    }

    /// Decodes the message from the JSON string.
    pub fn jsonDecode(
        input: []const u8,
        options: std.json.ParseOptions,
        allocator: std.mem.Allocator,
    ) !std.json.Parsed(@This()) {
        return protobuf.json.decode(@This(), input, options, allocator);
    }

    /// Encodes the message to a JSON string.
    pub fn jsonEncode(
        self: @This(),
        options: std.json.Stringify.Options,
        pb_options: protobuf.json.Options,
        allocator: std.mem.Allocator,
    ) ![]const u8 {
        return protobuf.json.encode(self, options, pb_options, allocator);
    }

    /// This method is used by std.json
    /// internally for deserialization. DO NOT RENAME!
    pub fn jsonParse(
        allocator: std.mem.Allocator,
        source: anytype,
        options: std.json.ParseOptions,
    ) !@This() {
        return protobuf.json.parse(@This(), allocator, source, options);
    }
};

/// Describes the physical path that a vehicle takes when it's not part of the (CSV) GTFS,
/// such as for a detour. Shapes belong to Trips, and consist of a sequence of shape points.
/// Tracing the points in order provides the path of the vehicle.  Shapes do not need to intercept
/// the location of Stops exactly, but all Stops on a trip should lie within a small distance of
/// the shape for that trip, i.e. close to straight line segments connecting the shape points
/// NOTE: This message is still experimental, and subject to change. It may be formally adopted in the future.
pub const Shape = struct {
    shape_id: ?[]const u8 = null,
    encoded_polyline: ?[]const u8 = null,

    pub const _desc_table = .{
        .shape_id = fd(1, .{ .scalar = .string }),
        .encoded_polyline = fd(2, .{ .scalar = .string }),
    };

    /// Encodes the message to the writer
    /// The allocator is used to generate submessages internally.
    /// Hence, an ArenaAllocator is a preferred choice if allocations are a bottleneck.
    pub fn encode(
        self: @This(),
        writer: *std.Io.Writer,
        allocator: std.mem.Allocator,
    ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
        return protobuf.encode(writer, allocator, self);
    }

    /// Decodes the message from the bytes read from the reader.
    pub fn decode(
        reader: *std.Io.Reader,
        allocator: std.mem.Allocator,
    ) (protobuf.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
        return protobuf.decode(@This(), reader, allocator);
    }

    /// Streaming pull-decoder: walks a `std.Io.Reader` one wire
    /// field at a time without allocating. See `src/stream.zig`.
    pub const StreamDecoder = protobuf.StreamDecoder(@This());

    /// Deinitializes and frees the memory associated with the message.
    pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
        return protobuf.deinit(allocator, self);
    }

    /// Duplicates the message.
    pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
        return protobuf.dupe(@This(), self, allocator);
    }

    /// Decodes the message from the JSON string.
    pub fn jsonDecode(
        input: []const u8,
        options: std.json.ParseOptions,
        allocator: std.mem.Allocator,
    ) !std.json.Parsed(@This()) {
        return protobuf.json.decode(@This(), input, options, allocator);
    }

    /// Encodes the message to a JSON string.
    pub fn jsonEncode(
        self: @This(),
        options: std.json.Stringify.Options,
        pb_options: protobuf.json.Options,
        allocator: std.mem.Allocator,
    ) ![]const u8 {
        return protobuf.json.encode(self, options, pb_options, allocator);
    }

    /// This method is used by std.json
    /// internally for deserialization. DO NOT RENAME!
    pub fn jsonParse(
        allocator: std.mem.Allocator,
        source: anytype,
        options: std.json.ParseOptions,
    ) !@This() {
        return protobuf.json.parse(@This(), allocator, source, options);
    }
};

/// Describes a stop which is served by trips. All fields are as described in the GTFS-Static specification.
/// NOTE: This message is still experimental, and subject to change. It may be formally adopted in the future.
pub const Stop = struct {
    stop_id: ?[]const u8 = null,
    stop_code: ?TranslatedString = null,
    stop_name: ?TranslatedString = null,
    tts_stop_name: ?TranslatedString = null,
    stop_desc: ?TranslatedString = null,
    stop_lat: ?f32 = null,
    stop_lon: ?f32 = null,
    zone_id: ?[]const u8 = null,
    stop_url: ?TranslatedString = null,
    parent_station: ?[]const u8 = null,
    stop_timezone: ?[]const u8 = null,
    wheelchair_boarding: ?Stop.WheelchairBoarding = .UNKNOWN,
    level_id: ?[]const u8 = null,
    platform_code: ?TranslatedString = null,

    pub const _desc_table = .{
        .stop_id = fd(1, .{ .scalar = .string }),
        .stop_code = fd(2, .submessage),
        .stop_name = fd(3, .submessage),
        .tts_stop_name = fd(4, .submessage),
        .stop_desc = fd(5, .submessage),
        .stop_lat = fd(6, .{ .scalar = .float }),
        .stop_lon = fd(7, .{ .scalar = .float }),
        .zone_id = fd(8, .{ .scalar = .string }),
        .stop_url = fd(9, .submessage),
        .parent_station = fd(11, .{ .scalar = .string }),
        .stop_timezone = fd(12, .{ .scalar = .string }),
        .wheelchair_boarding = fd(13, .@"enum"),
        .level_id = fd(14, .{ .scalar = .string }),
        .platform_code = fd(15, .submessage),
    };

    pub const WheelchairBoarding = enum(i32) {
        UNKNOWN = 0,
        AVAILABLE = 1,
        NOT_AVAILABLE = 2,
        _,
    };

    /// Encodes the message to the writer
    /// The allocator is used to generate submessages internally.
    /// Hence, an ArenaAllocator is a preferred choice if allocations are a bottleneck.
    pub fn encode(
        self: @This(),
        writer: *std.Io.Writer,
        allocator: std.mem.Allocator,
    ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
        return protobuf.encode(writer, allocator, self);
    }

    /// Decodes the message from the bytes read from the reader.
    pub fn decode(
        reader: *std.Io.Reader,
        allocator: std.mem.Allocator,
    ) (protobuf.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
        return protobuf.decode(@This(), reader, allocator);
    }

    /// Streaming pull-decoder: walks a `std.Io.Reader` one wire
    /// field at a time without allocating. See `src/stream.zig`.
    pub const StreamDecoder = protobuf.StreamDecoder(@This());

    /// Deinitializes and frees the memory associated with the message.
    pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
        return protobuf.deinit(allocator, self);
    }

    /// Duplicates the message.
    pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
        return protobuf.dupe(@This(), self, allocator);
    }

    /// Decodes the message from the JSON string.
    pub fn jsonDecode(
        input: []const u8,
        options: std.json.ParseOptions,
        allocator: std.mem.Allocator,
    ) !std.json.Parsed(@This()) {
        return protobuf.json.decode(@This(), input, options, allocator);
    }

    /// Encodes the message to a JSON string.
    pub fn jsonEncode(
        self: @This(),
        options: std.json.Stringify.Options,
        pb_options: protobuf.json.Options,
        allocator: std.mem.Allocator,
    ) ![]const u8 {
        return protobuf.json.encode(self, options, pb_options, allocator);
    }

    /// This method is used by std.json
    /// internally for deserialization. DO NOT RENAME!
    pub fn jsonParse(
        allocator: std.mem.Allocator,
        source: anytype,
        options: std.json.ParseOptions,
    ) !@This() {
        return protobuf.json.parse(@This(), allocator, source, options);
    }
};

/// NOTE: This field is still experimental, and subject to change. It may be formally adopted in the future.
pub const TripModifications = struct {
    selected_trips: std.ArrayList(TripModifications.SelectedTrips) = .empty,
    start_times: std.ArrayList([]const u8) = .empty,
    service_dates: std.ArrayList([]const u8) = .empty,
    modifications: std.ArrayList(TripModifications.Modification) = .empty,

    pub const _desc_table = .{
        .selected_trips = fd(1, .{ .repeated = .submessage }),
        .start_times = fd(2, .{ .repeated = .{ .scalar = .string } }),
        .service_dates = fd(3, .{ .repeated = .{ .scalar = .string } }),
        .modifications = fd(4, .{ .repeated = .submessage }),
    };

    /// A `Modification` message replaces a span of n stop times from each affected trip starting at `start_stop_selector`.
    pub const Modification = struct {
        start_stop_selector: ?StopSelector = null,
        end_stop_selector: ?StopSelector = null,
        propagated_modification_delay: ?i32 = 0,
        replacement_stops: std.ArrayList(ReplacementStop) = .empty,
        service_alert_id: ?[]const u8 = null,
        last_modified_time: ?u64 = null,

        pub const _desc_table = .{
            .start_stop_selector = fd(1, .submessage),
            .end_stop_selector = fd(2, .submessage),
            .propagated_modification_delay = fd(3, .{ .scalar = .int32 }),
            .replacement_stops = fd(4, .{ .repeated = .submessage }),
            .service_alert_id = fd(5, .{ .scalar = .string }),
            .last_modified_time = fd(6, .{ .scalar = .uint64 }),
        };

        /// Encodes the message to the writer
        /// The allocator is used to generate submessages internally.
        /// Hence, an ArenaAllocator is a preferred choice if allocations are a bottleneck.
        pub fn encode(
            self: @This(),
            writer: *std.Io.Writer,
            allocator: std.mem.Allocator,
        ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
            return protobuf.encode(writer, allocator, self);
        }

        /// Decodes the message from the bytes read from the reader.
        pub fn decode(
            reader: *std.Io.Reader,
            allocator: std.mem.Allocator,
        ) (protobuf.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
            return protobuf.decode(@This(), reader, allocator);
        }

        /// Streaming pull-decoder: walks a `std.Io.Reader` one wire
        /// field at a time without allocating. See `src/stream.zig`.
        pub const StreamDecoder = protobuf.StreamDecoder(@This());

        /// Deinitializes and frees the memory associated with the message.
        pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
            return protobuf.deinit(allocator, self);
        }

        /// Duplicates the message.
        pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
            return protobuf.dupe(@This(), self, allocator);
        }

        /// Decodes the message from the JSON string.
        pub fn jsonDecode(
            input: []const u8,
            options: std.json.ParseOptions,
            allocator: std.mem.Allocator,
        ) !std.json.Parsed(@This()) {
            return protobuf.json.decode(@This(), input, options, allocator);
        }

        /// Encodes the message to a JSON string.
        pub fn jsonEncode(
            self: @This(),
            options: std.json.Stringify.Options,
            pb_options: protobuf.json.Options,
            allocator: std.mem.Allocator,
        ) ![]const u8 {
            return protobuf.json.encode(self, options, pb_options, allocator);
        }

        /// This method is used by std.json
        /// internally for deserialization. DO NOT RENAME!
        pub fn jsonParse(
            allocator: std.mem.Allocator,
            source: anytype,
            options: std.json.ParseOptions,
        ) !@This() {
            return protobuf.json.parse(@This(), allocator, source, options);
        }
    };

    pub const SelectedTrips = struct {
        trip_ids: std.ArrayList([]const u8) = .empty,
        shape_id: ?[]const u8 = null,

        pub const _desc_table = .{
            .trip_ids = fd(1, .{ .repeated = .{ .scalar = .string } }),
            .shape_id = fd(2, .{ .scalar = .string }),
        };

        /// Encodes the message to the writer
        /// The allocator is used to generate submessages internally.
        /// Hence, an ArenaAllocator is a preferred choice if allocations are a bottleneck.
        pub fn encode(
            self: @This(),
            writer: *std.Io.Writer,
            allocator: std.mem.Allocator,
        ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
            return protobuf.encode(writer, allocator, self);
        }

        /// Decodes the message from the bytes read from the reader.
        pub fn decode(
            reader: *std.Io.Reader,
            allocator: std.mem.Allocator,
        ) (protobuf.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
            return protobuf.decode(@This(), reader, allocator);
        }

        /// Streaming pull-decoder: walks a `std.Io.Reader` one wire
        /// field at a time without allocating. See `src/stream.zig`.
        pub const StreamDecoder = protobuf.StreamDecoder(@This());

        /// Deinitializes and frees the memory associated with the message.
        pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
            return protobuf.deinit(allocator, self);
        }

        /// Duplicates the message.
        pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
            return protobuf.dupe(@This(), self, allocator);
        }

        /// Decodes the message from the JSON string.
        pub fn jsonDecode(
            input: []const u8,
            options: std.json.ParseOptions,
            allocator: std.mem.Allocator,
        ) !std.json.Parsed(@This()) {
            return protobuf.json.decode(@This(), input, options, allocator);
        }

        /// Encodes the message to a JSON string.
        pub fn jsonEncode(
            self: @This(),
            options: std.json.Stringify.Options,
            pb_options: protobuf.json.Options,
            allocator: std.mem.Allocator,
        ) ![]const u8 {
            return protobuf.json.encode(self, options, pb_options, allocator);
        }

        /// This method is used by std.json
        /// internally for deserialization. DO NOT RENAME!
        pub fn jsonParse(
            allocator: std.mem.Allocator,
            source: anytype,
            options: std.json.ParseOptions,
        ) !@This() {
            return protobuf.json.parse(@This(), allocator, source, options);
        }
    };

    /// Encodes the message to the writer
    /// The allocator is used to generate submessages internally.
    /// Hence, an ArenaAllocator is a preferred choice if allocations are a bottleneck.
    pub fn encode(
        self: @This(),
        writer: *std.Io.Writer,
        allocator: std.mem.Allocator,
    ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
        return protobuf.encode(writer, allocator, self);
    }

    /// Decodes the message from the bytes read from the reader.
    pub fn decode(
        reader: *std.Io.Reader,
        allocator: std.mem.Allocator,
    ) (protobuf.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
        return protobuf.decode(@This(), reader, allocator);
    }

    /// Streaming pull-decoder: walks a `std.Io.Reader` one wire
    /// field at a time without allocating. See `src/stream.zig`.
    pub const StreamDecoder = protobuf.StreamDecoder(@This());

    /// Deinitializes and frees the memory associated with the message.
    pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
        return protobuf.deinit(allocator, self);
    }

    /// Duplicates the message.
    pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
        return protobuf.dupe(@This(), self, allocator);
    }

    /// Decodes the message from the JSON string.
    pub fn jsonDecode(
        input: []const u8,
        options: std.json.ParseOptions,
        allocator: std.mem.Allocator,
    ) !std.json.Parsed(@This()) {
        return protobuf.json.decode(@This(), input, options, allocator);
    }

    /// Encodes the message to a JSON string.
    pub fn jsonEncode(
        self: @This(),
        options: std.json.Stringify.Options,
        pb_options: protobuf.json.Options,
        allocator: std.mem.Allocator,
    ) ![]const u8 {
        return protobuf.json.encode(self, options, pb_options, allocator);
    }

    /// This method is used by std.json
    /// internally for deserialization. DO NOT RENAME!
    pub fn jsonParse(
        allocator: std.mem.Allocator,
        source: anytype,
        options: std.json.ParseOptions,
    ) !@This() {
        return protobuf.json.parse(@This(), allocator, source, options);
    }
};

/// NOTE: This field is still experimental, and subject to change. It may be formally adopted in the future.
/// Select a stop by stop sequence or by stop_id. At least one of the two values must be provided.
pub const StopSelector = struct {
    stop_sequence: ?u32 = null,
    stop_id: ?[]const u8 = null,

    pub const _desc_table = .{
        .stop_sequence = fd(1, .{ .scalar = .uint32 }),
        .stop_id = fd(2, .{ .scalar = .string }),
    };

    /// Encodes the message to the writer
    /// The allocator is used to generate submessages internally.
    /// Hence, an ArenaAllocator is a preferred choice if allocations are a bottleneck.
    pub fn encode(
        self: @This(),
        writer: *std.Io.Writer,
        allocator: std.mem.Allocator,
    ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
        return protobuf.encode(writer, allocator, self);
    }

    /// Decodes the message from the bytes read from the reader.
    pub fn decode(
        reader: *std.Io.Reader,
        allocator: std.mem.Allocator,
    ) (protobuf.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
        return protobuf.decode(@This(), reader, allocator);
    }

    /// Streaming pull-decoder: walks a `std.Io.Reader` one wire
    /// field at a time without allocating. See `src/stream.zig`.
    pub const StreamDecoder = protobuf.StreamDecoder(@This());

    /// Deinitializes and frees the memory associated with the message.
    pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
        return protobuf.deinit(allocator, self);
    }

    /// Duplicates the message.
    pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
        return protobuf.dupe(@This(), self, allocator);
    }

    /// Decodes the message from the JSON string.
    pub fn jsonDecode(
        input: []const u8,
        options: std.json.ParseOptions,
        allocator: std.mem.Allocator,
    ) !std.json.Parsed(@This()) {
        return protobuf.json.decode(@This(), input, options, allocator);
    }

    /// Encodes the message to a JSON string.
    pub fn jsonEncode(
        self: @This(),
        options: std.json.Stringify.Options,
        pb_options: protobuf.json.Options,
        allocator: std.mem.Allocator,
    ) ![]const u8 {
        return protobuf.json.encode(self, options, pb_options, allocator);
    }

    /// This method is used by std.json
    /// internally for deserialization. DO NOT RENAME!
    pub fn jsonParse(
        allocator: std.mem.Allocator,
        source: anytype,
        options: std.json.ParseOptions,
    ) !@This() {
        return protobuf.json.parse(@This(), allocator, source, options);
    }
};

/// NOTE: This field is still experimental, and subject to change. It may be formally adopted in the future.
pub const ReplacementStop = struct {
    travel_time_to_stop: ?i32 = null,
    stop_id: ?[]const u8 = null,

    pub const _desc_table = .{
        .travel_time_to_stop = fd(1, .{ .scalar = .int32 }),
        .stop_id = fd(2, .{ .scalar = .string }),
    };

    /// Encodes the message to the writer
    /// The allocator is used to generate submessages internally.
    /// Hence, an ArenaAllocator is a preferred choice if allocations are a bottleneck.
    pub fn encode(
        self: @This(),
        writer: *std.Io.Writer,
        allocator: std.mem.Allocator,
    ) (std.Io.Writer.Error || std.mem.Allocator.Error)!void {
        return protobuf.encode(writer, allocator, self);
    }

    /// Decodes the message from the bytes read from the reader.
    pub fn decode(
        reader: *std.Io.Reader,
        allocator: std.mem.Allocator,
    ) (protobuf.DecodingError || std.Io.Reader.Error || std.mem.Allocator.Error)!@This() {
        return protobuf.decode(@This(), reader, allocator);
    }

    /// Streaming pull-decoder: walks a `std.Io.Reader` one wire
    /// field at a time without allocating. See `src/stream.zig`.
    pub const StreamDecoder = protobuf.StreamDecoder(@This());

    /// Deinitializes and frees the memory associated with the message.
    pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
        return protobuf.deinit(allocator, self);
    }

    /// Duplicates the message.
    pub fn dupe(self: @This(), allocator: std.mem.Allocator) std.mem.Allocator.Error!@This() {
        return protobuf.dupe(@This(), self, allocator);
    }

    /// Decodes the message from the JSON string.
    pub fn jsonDecode(
        input: []const u8,
        options: std.json.ParseOptions,
        allocator: std.mem.Allocator,
    ) !std.json.Parsed(@This()) {
        return protobuf.json.decode(@This(), input, options, allocator);
    }

    /// Encodes the message to a JSON string.
    pub fn jsonEncode(
        self: @This(),
        options: std.json.Stringify.Options,
        pb_options: protobuf.json.Options,
        allocator: std.mem.Allocator,
    ) ![]const u8 {
        return protobuf.json.encode(self, options, pb_options, allocator);
    }

    /// This method is used by std.json
    /// internally for deserialization. DO NOT RENAME!
    pub fn jsonParse(
        allocator: std.mem.Allocator,
        source: anytype,
        options: std.json.ParseOptions,
    ) !@This() {
        return protobuf.json.parse(@This(), allocator, source, options);
    }
};
